---
- name: Deploy VLAN Infrastructure
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VLANs
      command: "echo 'Create VLAN {{ item }}'"
      loop: [10, 20, 30, 40, 50]
      register: vlans

    - name: Deploy AD Server
      hosts: windows_servers
      tasks:
        - name: Install Active Directory Server
          win_shell: |
            # Install AD server software
            # Add domain controller configuration
            # Configure necessary settings
          loop: "{{ vlans.results }}"

    - name: Deploy Apache Web Server
      hosts: linux_servers
      tasks:
        - name: Install Apache Web Server
          apt:
            name: apache2
            state: present
        - name: Start Apache service
          service:
            name: apache2
            state: started  
          loop: "{{ vlans.results }}"

    - name: Deploy Linux Workstations
      hosts: linux_workstations
      tasks:
          # Install required packages and configure the workstation
        - name: Deploy Linux Host
          hosts: target_linux_host
          become: yes
          tasks:
            - name: Update package cache
              apt:
                update_cache: yes
              when: ansible_os_family == 'Debian'
        
            - name: Install required packages
              apt:
                name: "{{ item }}"
                state: present
              loop:
                - package1
                - package2
                - package3
              when: ansible_os_family == 'Debian'
        
            - name: Update package cache
              yum:
                name: '*'
                state: latest
              when: ansible_os_family == 'RedHat'
        
            - name: Install required packages
              yum:
                name: "{{ item }}"
                state: present
              loop:
                - package1
                - package2
                - package3
              when: ansible_os_family == 'RedHat'
        
            - name: Configure firewall rules
              firewalld:
                port: 80/tcp
                permanent: yes
                state: enabled
                
          loop: "{{ vlans.results }}"

    - name: Deploy Windows 10 Workstations
      hosts: windows_workstations
      tasks:
        - name: Install Windows 10 Workstation
          win_shell: |
            # Install Windows 10 OS
            # Configure necessary settings
          loop: "{{ vlans.results }}"
